/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 04-Apr-2026 01:20:19
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 I 型
 * 分子 长度  : 11
 * 分母 长度  : 11
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Matlab\R2024a\extern\include\tmwtypes.h 
 */
const int NL = 11;
const real64_T NUM[11] = {
   0.001921073607887, -0.01582233398195,  0.06173168982294,  -0.1491538305649,
     0.2463093607783,  -0.2899614251408,   0.2463093607783,  -0.1491538305649,
    0.06173168982294, -0.01582233398195, 0.001921073607887
};
const int DL = 11;
const real64_T DEN[11] = {
                   1,   -1.832786262737,   -1.224855861324,    2.826160440524,
      1.632584744955,   -2.486457890674,   -1.233681781788,    1.058111500771,
     0.5467512933005,  -0.1849415421185,  -0.1008741467245
};
